### ISSUE TITLE
Unable to configure keys

### ISSUE THREAD

**Issue by ghost** [neuromancer/avp#1]
Hi,

I managed to compile it and get it up and running on Linux, using the data files from the GOG release.
Everything appears to work fine, except that I'm unable to configure any keys.

As soon as I select a control I want to modify (by pressing ENTER), the bound key is cleared and 'confirmed', leaving me unable to specify the key I want to use. The default controls are unworkable for me and AFAIK the controls are stored in a binary format, so I can't edit them there either.

Is this a known issue, and can I fix it?

Regards

**Comment by neuromancer** [comment]
Can you please try using [the original version](https://icculus.org/avp/files/avp-20170505-a1.tar.gz)? I want to know if this issue is cause by some modification I did.

**Comment by neuromancer** [comment]
Any updates?

**Comment by ghost** [comment]
Hi,

Sorry for the lack of news! I compiled that version, but it crashes on startup.

**Comment by johndoe71rus** [comment]
can confirm, can't change some keyboard keys.
example:
first and second attack mouse1 and mouse2. my mouse don't work in game. Can't look or move. And game run in window, not fullscreen.
i choose line first attack, press enter, field blank and space blinking. but then i press mlb no reactions. but i cange first attaxk to M key.
i test with usb mouse and synaptic touchpad at my laptop. 
test yestorday git build and avp_20170505, avp gold english.
