### ISSUE TITLE
can't run 

### ISSUE THREAD

**Issue by johndoe71rus** [neuromancer/avp#2]
just build from git. 
Calculate linux 17.12.2

test@test ~/game/aliensvspredator $ ./avp
segmentation fault

file dx_error.log
dx_line_log: /home/test/build/game/avp/src/avp/win95/ffstdio.cpp/140
dx_strf_log: Loaded FastFile: fastfile/Tex37.FFL
(for directory: graphics\Menus)

dx_line_log: /home/test/build/game/avp/src/avp/win95/ffstdio.cpp/140
dx_strf_log: Loaded FastFile: fastfile/Tex1.FFL
(for directory: Graphics\Common)

try change Tex1.FFL and Tex37.FFL to eng version, no luck.
my original md5 without changes 
https://paste.ubuntu.com/p/3xTj8xyx2J/

**Comment by neuromancer** [comment]
Can you please try using the [original version](https://icculus.org/avp/files/avp-20170505-a1.tar.gz)? I want to know if this issue is cause by some modification I did.

**Comment by johndoe71rus** [comment]
the same https://paste.ubuntu.com/p/hXB4vDVf5q/
game version Aliens versus Predator Classic 2000
try find Gold edition

**Comment by johndoe71rus** [comment]
eng Gold edition work 

```
test@test ~/game/avpgold $ ./avp 
AL lib: (EE) alc_cleanup: 1 device not closed
test@test ~/game/avpgold $ ./avp_20170505 
AL lib: (EE) alc_cleanup: 1 device not closed
test@test ~/game/avpgold $ 
```
oh it hase log too 
https://paste.ubuntu.com/p/QWF4nyzfkq/

**Comment by johndoe71rus** [comment]
but rus version has error 
```
test@test ~/game/avpgold_rus $ ./avp 
ERROR: I am going to give up now, because I don't like your font!
Font Size: 21 x 6864
AL lib: (EE) alc_cleanup: 1 device not closed
test@test ~/game/avpgold_rus $ ./avp_20170505 
ERROR: I am going to give up now, because I don't like your font!
Font Size: 21 x 6864
AL lib: (EE) alc_cleanup: 1 device not closed
```
https://paste.ubuntu.com/p/vXDXwf3PSp/
